# ============================================
# 📁 VERIFICAR/CREAR: Frontend/netlify.toml
# ============================================

[build]
  # Directorio base donde está package.json (Frontend/frontend/)
  base = "frontend"
  
  # Comando para construir el proyecto
  command = "npm run build:prod"
  
  # Directorio donde se generan los archivos (Frontend/frontend/dist/frontend)
  publish = "dist/frontend"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# ⚠️ MUY IMPORTANTE: Redirecciones para Angular SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"