# ============================================
# 游늬 CREAR: Frontend/netlify.toml
# ============================================

[build]
  # Directorio base donde est치 package.json
  base = "frontend"
  
  # Comando para construir el proyecto
  command = "npm run build:prod"
  
  # Directorio donde se generan los archivos de producci칩n
  publish = "frontend/dist/frontend"

[build.environment]
  # Versi칩n de Node.js para el build
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Redirecciones para Angular SPA (MUY IMPORTANTE)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para archivos est치ticos (cache)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para JS y CSS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Variables de entorno para producci칩n
[context.production.environment]
  NODE_ENV = "production"
  
# Variables para preview branches
[context.deploy-preview.environment]
  NODE_ENV = "development"